// Code generated by ggconfig. DO NOT EDIT.

package gconfig

import (
	"os"
	
	"github.com/apopov-app/ggconfig/runtime"
)

// ===== ENV Implementation =====

type databaseEnvConfig struct{
	mapKey func(string) string
}


func (c *databaseEnvConfig) Host(defaultValue string) (string, bool) {
	if value := os.Getenv(c.mapKey("DATABASE_HOST")); value != "" {
		return value, true
	}
	return defaultValue, false
}

func (c *databaseEnvConfig) Port(defaultValue string) (string, bool) {
	if value := os.Getenv(c.mapKey("DATABASE_PORT")); value != "" {
		return value, true
	}
	return defaultValue, false
}

func (c *databaseEnvConfig) User(defaultValue string) (string, bool) {
	if value := os.Getenv(c.mapKey("DATABASE_USER")); value != "" {
		return value, true
	}
	return defaultValue, false
}

func (c *databaseEnvConfig) Password(defaultValue string) (string, bool) {
	if value := os.Getenv(c.mapKey("DATABASE_PASSWORD")); value != "" {
		return value, true
	}
	return defaultValue, false
}

func (c *databaseEnvConfig) Name(defaultValue string) (string, bool) {
	if value := os.Getenv(c.mapKey("DATABASE_NAME")); value != "" {
		return value, true
	}
	return defaultValue, false
}

func (c *databaseEnvConfig) SSLMode(defaultValue string) (string, bool) {
	if value := os.Getenv(c.mapKey("DATABASE_SSL_MODE")); value != "" {
		return value, true
	}
	return defaultValue, false
}


func NewDatabaseConfigEnvConfig() *databaseEnvConfig {
	return NewDatabaseConfigEnvConfigWithMap(nil)
}

func NewDatabaseConfigEnvConfigWithMap(mapKey func(string) string) *databaseEnvConfig {
	if mapKey == nil {
		mapKey = func(k string) string { return k }
	}
	return &databaseEnvConfig{mapKey: mapKey}
}

// ===== YAML Implementation =====

type databaseYAMLConfig struct {
	y *runtime.YAML
	err error
}

func NewDatabaseConfigYAMLConfig(path string) *databaseYAMLConfig {
	b, err := os.ReadFile(path)
	if err != nil {
		return &databaseYAMLConfig{y: &runtime.YAML{}, err: err}
	}
	y, err := runtime.ParseYAML(b)
	if err != nil {
		return &databaseYAMLConfig{y: &runtime.YAML{}, err: err}
	}
	return &databaseYAMLConfig{y: y}
}

func NewDatabaseConfigYAMLConfigParsed(y *runtime.YAML) *databaseYAMLConfig {
	return &databaseYAMLConfig{
		y: y,
	}
}

func (c *databaseYAMLConfig) Err() error { return c.err }


func (c *databaseYAMLConfig) Host(defaultValue string) (string, bool) {
	// Алиасные секции
	// Основная секция database
	if v, ok := c.y.GetString("database", "host"); ok {
		return v, true
	}
	return defaultValue, false
}

func (c *databaseYAMLConfig) Port(defaultValue string) (string, bool) {
	// Алиасные секции
	// Основная секция database
	if v, ok := c.y.GetString("database", "port"); ok {
		return v, true
	}
	return defaultValue, false
}

func (c *databaseYAMLConfig) User(defaultValue string) (string, bool) {
	// Алиасные секции
	// Основная секция database
	if v, ok := c.y.GetString("database", "user"); ok {
		return v, true
	}
	return defaultValue, false
}

func (c *databaseYAMLConfig) Password(defaultValue string) (string, bool) {
	// Алиасные секции
	// Основная секция database
	if v, ok := c.y.GetString("database", "password"); ok {
		return v, true
	}
	return defaultValue, false
}

func (c *databaseYAMLConfig) Name(defaultValue string) (string, bool) {
	// Алиасные секции
	// Основная секция database
	if v, ok := c.y.GetString("database", "name"); ok {
		return v, true
	}
	return defaultValue, false
}

func (c *databaseYAMLConfig) SSLMode(defaultValue string) (string, bool) {
	// Алиасные секции
	// Основная секция database
	if v, ok := c.y.GetString("database", "sslmode"); ok {
		return v, true
	}
	return defaultValue, false
}


// ===== Mock Implementation =====

type databaseMockConfig struct{}


func (c *databaseMockConfig) Host(defaultValue string) (string, bool) {
	return defaultValue, false
}

func (c *databaseMockConfig) Port(defaultValue string) (string, bool) {
	return defaultValue, false
}

func (c *databaseMockConfig) User(defaultValue string) (string, bool) {
	return defaultValue, false
}

func (c *databaseMockConfig) Password(defaultValue string) (string, bool) {
	return defaultValue, false
}

func (c *databaseMockConfig) Name(defaultValue string) (string, bool) {
	return defaultValue, false
}

func (c *databaseMockConfig) SSLMode(defaultValue string) (string, bool) {
	return defaultValue, false
}


func NewDatabaseConfigMock() *databaseMockConfig {
	return &databaseMockConfig{}
}

// ===== Composite Implementation =====

type databaseAllConfig struct {
	sources []interface{
		Host(defaultValue string) (string, bool)
		Port(defaultValue string) (string, bool)
		User(defaultValue string) (string, bool)
		Password(defaultValue string) (string, bool)
		Name(defaultValue string) (string, bool)
		SSLMode(defaultValue string) (string, bool)
	}
}

func NewDatabaseConfigAll(sources ...interface{
	Host(defaultValue string) (string, bool)
	Port(defaultValue string) (string, bool)
	User(defaultValue string) (string, bool)
	Password(defaultValue string) (string, bool)
	Name(defaultValue string) (string, bool)
	SSLMode(defaultValue string) (string, bool)
}) *databaseAllConfig {
	return &databaseAllConfig{sources: sources}
}


func (c *databaseAllConfig) Host(defaultValue string) (string, bool) {
	for _, s := range c.sources {
		v, ok := s.Host(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *databaseAllConfig) Port(defaultValue string) (string, bool) {
	for _, s := range c.sources {
		v, ok := s.Port(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *databaseAllConfig) User(defaultValue string) (string, bool) {
	for _, s := range c.sources {
		v, ok := s.User(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *databaseAllConfig) Password(defaultValue string) (string, bool) {
	for _, s := range c.sources {
		v, ok := s.Password(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *databaseAllConfig) Name(defaultValue string) (string, bool) {
	for _, s := range c.sources {
		v, ok := s.Name(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *databaseAllConfig) SSLMode(defaultValue string) (string, bool) {
	for _, s := range c.sources {
		v, ok := s.SSLMode(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}



func init() {
	Register("database", Provider{
		Package: "database",
		NewAllFromParsed: func(y *runtime.YAML, mapKey func(string) string) any {
			envCfg := NewDatabaseConfigEnvConfigWithMap(mapKey)
			yamlCfg := NewDatabaseConfigYAMLConfigParsed(y)
			return NewDatabaseConfigAll(envCfg, yamlCfg)
		},
	})
}

// GetDatabase returns the concrete AllConfig type for this package.
// It can be passed anywhere the original interface is expected (structural typing).
func (g *GlobalConfig) GetDatabase() (*databaseAllConfig, bool) {
	registryMu.RLock()
	p, ok := registry["database"]
	registryMu.RUnlock()
	if !ok || p.NewAllFromParsed == nil {
		return nil, false
	}
	v := p.NewAllFromParsed(g.y, g.mapKey)
	cfg, ok := v.(*databaseAllConfig)
	return cfg, ok
}

