// Code generated by ggconfig. DO NOT EDIT.

package gconfig

import (
	
	"os"
	"strconv"
	"github.com/apopov-app/ggconfig/runtime"
	
)

// ===== ENV Implementation =====

type internal_serverEnvConfig struct{
	mapKey func(string) string
}


func (c *internal_serverEnvConfig) Port(defaultValue int) (int, bool) {
	if value := os.Getenv(c.mapKey("SERVER_PORT")); value != "" {
		if intValue, err := strconv.Atoi(value); err == nil {
			return intValue, true
		}
	}
	return defaultValue, false
}

func (c *internal_serverEnvConfig) Host(defaultValue string) (string, bool) {
	if value := os.Getenv(c.mapKey("SERVER_ADDRESS_ALIASE")); value != "" {
    return value, true
}
	if value := os.Getenv(c.mapKey("SERVER_HOST")); value != "" {
		return value, true
	}
	return defaultValue, false
}

func (c *internal_serverEnvConfig) ReadTimeout(defaultValue int) (int, bool) {
	if value := os.Getenv(c.mapKey("SERVER_READ_TIMEOUT")); value != "" {
		if intValue, err := strconv.Atoi(value); err == nil {
			return intValue, true
		}
	}
	return defaultValue, false
}

func (c *internal_serverEnvConfig) WriteTimeout(defaultValue int) (int, bool) {
	if value := os.Getenv(c.mapKey("SERVER_WRITE_TIMEOUT")); value != "" {
		if intValue, err := strconv.Atoi(value); err == nil {
			return intValue, true
		}
	}
	return defaultValue, false
}


func NewInternalServerConfigEnvConfig() *internal_serverEnvConfig {
	return NewInternalServerConfigEnvConfigWithMap(nil)
}

func NewInternalServerConfigEnvConfigWithMap(mapKey func(string) string) *internal_serverEnvConfig {
	if mapKey == nil {
		mapKey = func(k string) string { return k }
	}
	return &internal_serverEnvConfig{mapKey: mapKey}
}

// ===== YAML Implementation =====

type internal_serverYAMLConfig struct {
	y *runtime.YAML
	err error
}

func NewInternalServerConfigYAMLConfig(path string) *internal_serverYAMLConfig {
	b, err := os.ReadFile(path)
	if err != nil {
		return &internal_serverYAMLConfig{y: &runtime.YAML{}, err: err}
	}
	y, err := runtime.ParseYAML(b)
	if err != nil {
		return &internal_serverYAMLConfig{y: &runtime.YAML{}, err: err}
	}
	return &internal_serverYAMLConfig{y: y}
}

func NewInternalServerConfigYAMLConfigParsed(y *runtime.YAML) *internal_serverYAMLConfig {
	return &internal_serverYAMLConfig{
		y: y,
	}
}

func (c *internal_serverYAMLConfig) Err() error { return c.err }


func (c *internal_serverYAMLConfig) Port(defaultValue int) (int, bool) {
	// Алиасные секции
	
	// Основная секция server
	if v, ok := c.y.GetInt("server", "port"); ok {
		return v, true
	}
	return defaultValue, false
}

func (c *internal_serverYAMLConfig) Host(defaultValue string) (string, bool) {
	// Алиасные секции
	
	// Основная секция server
	if v, ok := c.y.GetString("server", "host"); ok {
		return v, true
		}
	return defaultValue, false
}

func (c *internal_serverYAMLConfig) ReadTimeout(defaultValue int) (int, bool) {
	// Алиасные секции
	
	// Основная секция server
	if v, ok := c.y.GetInt("server", "readtimeout"); ok {
		return v, true
	}
	return defaultValue, false
}

func (c *internal_serverYAMLConfig) WriteTimeout(defaultValue int) (int, bool) {
	// Алиасные секции
	
	// Основная секция server
	if v, ok := c.y.GetInt("server", "writetimeout"); ok {
		return v, true
	}
	return defaultValue, false
}


// ===== Mock Implementation =====

type internal_serverMockConfig struct{}


func (c *internal_serverMockConfig) Port(defaultValue int) (int, bool) {
	return defaultValue, false
}

func (c *internal_serverMockConfig) Host(defaultValue string) (string, bool) {
	return defaultValue, false
}

func (c *internal_serverMockConfig) ReadTimeout(defaultValue int) (int, bool) {
	return defaultValue, false
}

func (c *internal_serverMockConfig) WriteTimeout(defaultValue int) (int, bool) {
	return defaultValue, false
}


func NewInternalServerConfigMock() *internal_serverMockConfig {
	return &internal_serverMockConfig{}
}

// ===== Composite Implementation =====

type internal_serverAllConfig struct {
	sources []interface{
		Port(defaultValue int) (int, bool)
		Host(defaultValue string) (string, bool)
		ReadTimeout(defaultValue int) (int, bool)
		WriteTimeout(defaultValue int) (int, bool)
	}
}

func NewInternalServerConfigAll(sources ...interface{
	Port(defaultValue int) (int, bool)
	Host(defaultValue string) (string, bool)
	ReadTimeout(defaultValue int) (int, bool)
	WriteTimeout(defaultValue int) (int, bool)
}) *internal_serverAllConfig {
	return &internal_serverAllConfig{sources: sources}
}


func (c *internal_serverAllConfig) Port(defaultValue int) (int, bool) {
	for _, s := range c.sources {
		v, ok := s.Port(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *internal_serverAllConfig) Host(defaultValue string) (string, bool) {
	for _, s := range c.sources {
		v, ok := s.Host(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *internal_serverAllConfig) ReadTimeout(defaultValue int) (int, bool) {
	for _, s := range c.sources {
		v, ok := s.ReadTimeout(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *internal_serverAllConfig) WriteTimeout(defaultValue int) (int, bool) {
	for _, s := range c.sources {
		v, ok := s.WriteTimeout(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}



func init() {
	Register("internal_server", Provider{
		Package: "internal_server",
		NewAllFromParsed: func(y *runtime.YAML, mapKey func(string) string) any {
			envCfg := NewInternalServerConfigEnvConfigWithMap(mapKey)
			yamlCfg := NewInternalServerConfigYAMLConfigParsed(y)
			return NewInternalServerConfigAll(envCfg, yamlCfg)
		},
	})
}

// GetInternalServer returns the concrete AllConfig type for this package.
// It can be passed anywhere the original interface is expected (structural typing).
func (g *GlobalConfig) GetInternalServer() (*internal_serverAllConfig, bool) {
	registryMu.RLock()
	p, ok := registry["internal_server"]
	registryMu.RUnlock()
	if !ok || p.NewAllFromParsed == nil {
		return nil, false
	}
	v := p.NewAllFromParsed(g.y, g.mapKey)
	cfg, ok := v.(*internal_serverAllConfig)
	return cfg, ok
}

