// Code generated by ggconfig. DO NOT EDIT.

package gconfig

import (
	"os"
	"strconv"
	"github.com/apopov-app/ggconfig/runtime"
)

// ===== ENV Implementation =====

type serverEnvConfig struct{
	mapKey func(string) string
}


func (c *serverEnvConfig) Port(defaultValue int) (int, bool) {
	if value := os.Getenv(c.mapKey("SERVER_PORT")); value != "" {
		if intValue, err := strconv.Atoi(value); err == nil {
			return intValue, true
		}
	}
	return defaultValue, false
}

func (c *serverEnvConfig) Host(defaultValue string) (string, bool) {
	if value := os.Getenv(c.mapKey("SERVER_ADDRESS_ALIASE")); value != "" {
    return value, true
}
	if value := os.Getenv(c.mapKey("SERVER_HOST")); value != "" {
		return value, true
	}
	return defaultValue, false
}

func (c *serverEnvConfig) ReadTimeout(defaultValue int) (int, bool) {
	if value := os.Getenv(c.mapKey("SERVER_READ_TIMEOUT")); value != "" {
		if intValue, err := strconv.Atoi(value); err == nil {
			return intValue, true
		}
	}
	return defaultValue, false
}

func (c *serverEnvConfig) WriteTimeout(defaultValue int) (int, bool) {
	if value := os.Getenv(c.mapKey("SERVER_WRITE_TIMEOUT")); value != "" {
		if intValue, err := strconv.Atoi(value); err == nil {
			return intValue, true
		}
	}
	return defaultValue, false
}


func NewServerConfigEnvConfig() *serverEnvConfig {
	return NewServerConfigEnvConfigWithMap(nil)
}

func NewServerConfigEnvConfigWithMap(mapKey func(string) string) *serverEnvConfig {
	if mapKey == nil {
		mapKey = func(k string) string { return k }
	}
	return &serverEnvConfig{mapKey: mapKey}
}

// ===== YAML Implementation =====

type serverYAMLConfig struct {
	y *runtime.YAML
	err error
}

func NewServerConfigYAMLConfig(path string) *serverYAMLConfig {
	b, err := os.ReadFile(path)
	if err != nil {
		return &serverYAMLConfig{y: &runtime.YAML{}, err: err}
	}
	y, err := runtime.ParseYAML(b)
	if err != nil {
		return &serverYAMLConfig{y: &runtime.YAML{}, err: err}
	}
	return &serverYAMLConfig{y: y}
}

func NewServerConfigYAMLConfigParsed(y *runtime.YAML) *serverYAMLConfig {
	return &serverYAMLConfig{
		y: y,
	}
}

func (c *serverYAMLConfig) Err() error { return c.err }


func (c *serverYAMLConfig) Port(defaultValue int) (int, bool) {
	// Алиасные секции
	// Основная секция server
	if v, ok := c.y.GetInt("server", "port"); ok {
		return v, true
	}
	return defaultValue, false
}

func (c *serverYAMLConfig) Host(defaultValue string) (string, bool) {
	// Алиасные секции
	// Основная секция server
	if v, ok := c.y.GetString("server", "host"); ok {
		return v, true
	}
	return defaultValue, false
}

func (c *serverYAMLConfig) ReadTimeout(defaultValue int) (int, bool) {
	// Алиасные секции
	// Основная секция server
	if v, ok := c.y.GetInt("server", "readtimeout"); ok {
		return v, true
	}
	return defaultValue, false
}

func (c *serverYAMLConfig) WriteTimeout(defaultValue int) (int, bool) {
	// Алиасные секции
	// Основная секция server
	if v, ok := c.y.GetInt("server", "writetimeout"); ok {
		return v, true
	}
	return defaultValue, false
}


// ===== Mock Implementation =====

type serverMockConfig struct{}


func (c *serverMockConfig) Port(defaultValue int) (int, bool) {
	return defaultValue, false
}

func (c *serverMockConfig) Host(defaultValue string) (string, bool) {
	return defaultValue, false
}

func (c *serverMockConfig) ReadTimeout(defaultValue int) (int, bool) {
	return defaultValue, false
}

func (c *serverMockConfig) WriteTimeout(defaultValue int) (int, bool) {
	return defaultValue, false
}


func NewServerConfigMock() *serverMockConfig {
	return &serverMockConfig{}
}

// ===== Composite Implementation =====

type serverAllConfig struct {
	sources []interface{
		Port(defaultValue int) (int, bool)
		Host(defaultValue string) (string, bool)
		ReadTimeout(defaultValue int) (int, bool)
		WriteTimeout(defaultValue int) (int, bool)
	}
}

func NewServerConfigAll(sources ...interface{
	Port(defaultValue int) (int, bool)
	Host(defaultValue string) (string, bool)
	ReadTimeout(defaultValue int) (int, bool)
	WriteTimeout(defaultValue int) (int, bool)
}) *serverAllConfig {
	return &serverAllConfig{sources: sources}
}


func (c *serverAllConfig) Port(defaultValue int) (int, bool) {
	for _, s := range c.sources {
		v, ok := s.Port(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *serverAllConfig) Host(defaultValue string) (string, bool) {
	for _, s := range c.sources {
		v, ok := s.Host(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *serverAllConfig) ReadTimeout(defaultValue int) (int, bool) {
	for _, s := range c.sources {
		v, ok := s.ReadTimeout(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *serverAllConfig) WriteTimeout(defaultValue int) (int, bool) {
	for _, s := range c.sources {
		v, ok := s.WriteTimeout(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}



func init() {
	Register("server", Provider{
		Package: "server",
		NewAllFromParsed: func(y *runtime.YAML, mapKey func(string) string) any {
			envCfg := NewServerConfigEnvConfigWithMap(mapKey)
			yamlCfg := NewServerConfigYAMLConfigParsed(y)
			return NewServerConfigAll(envCfg, yamlCfg)
		},
	})
}

// GetServer returns the concrete AllConfig type for this package.
// It can be passed anywhere the original interface is expected (structural typing).
func (g *GlobalConfig) GetServer() (*serverAllConfig, bool) {
	registryMu.RLock()
	p, ok := registry["server"]
	registryMu.RUnlock()
	if !ok || p.NewAllFromParsed == nil {
		return nil, false
	}
	v := p.NewAllFromParsed(g.y, g.mapKey)
	cfg, ok := v.(*serverAllConfig)
	return cfg, ok
}

