// Code generated by ggconfig. DO NOT EDIT.

package gconfig

import (
	"os"
	"strconv"
	"gopkg.in/yaml.v3"
)

// ===== ENV Implementation =====

type serverEnvConfig struct{}


func (c *serverEnvConfig) Port(defaultValue int) int {
	if value := os.Getenv("SERVER_PORT"); value != "" {
		if intValue, err := strconv.Atoi(value); err == nil {
			return intValue
		}
	}
	return defaultValue
}

func (c *serverEnvConfig) Host(defaultValue string) string {
	if value := os.Getenv("SERVER_ADDRESS_ALIASE"); value != "" {
    return value
}
	if value := os.Getenv("SERVER_HOST"); value != "" {
		return value
	}
	return defaultValue
}

func (c *serverEnvConfig) ReadTimeout(defaultValue int) int {
	if value := os.Getenv("SERVER_READ_TIMEOUT"); value != "" {
		if intValue, err := strconv.Atoi(value); err == nil {
			return intValue
		}
	}
	return defaultValue
}

func (c *serverEnvConfig) WriteTimeout(defaultValue int) int {
	if value := os.Getenv("SERVER_WRITE_TIMEOUT"); value != "" {
		if intValue, err := strconv.Atoi(value); err == nil {
			return intValue
		}
	}
	return defaultValue
}


func NewServerConfig() *serverEnvConfig {
	return &serverEnvConfig{}
}

// ===== YAML Implementation =====

type serverYAMLConfig struct {
	data []byte
}

func NewServerConfigYAML(data []byte) *serverYAMLConfig {
	return &serverYAMLConfig{
		data: data,
	}
}


func (c *serverYAMLConfig) Port(defaultValue int) int {
	var config map[string]interface{}
	if err := yaml.Unmarshal(c.data, &config); err != nil {
		return defaultValue
	}

	// Алиасные секции

	// Основная секция server
	if section, ok := config["server"].(map[string]interface{}); ok {
		if value, ok := section["port"].(int); ok {
			return value
		}
	}

	return defaultValue
}

func (c *serverYAMLConfig) Host(defaultValue string) string {
	var config map[string]interface{}
	if err := yaml.Unmarshal(c.data, &config); err != nil {
		return defaultValue
	}

	// Алиасные секции

	// Основная секция server
	if section, ok := config["server"].(map[string]interface{}); ok {
		if value, ok := section["host"].(string); ok {
			return value
		}
	}

	return defaultValue
}

func (c *serverYAMLConfig) ReadTimeout(defaultValue int) int {
	var config map[string]interface{}
	if err := yaml.Unmarshal(c.data, &config); err != nil {
		return defaultValue
	}

	// Алиасные секции

	// Основная секция server
	if section, ok := config["server"].(map[string]interface{}); ok {
		if value, ok := section["readtimeout"].(int); ok {
			return value
		}
	}

	return defaultValue
}

func (c *serverYAMLConfig) WriteTimeout(defaultValue int) int {
	var config map[string]interface{}
	if err := yaml.Unmarshal(c.data, &config); err != nil {
		return defaultValue
	}

	// Алиасные секции

	// Основная секция server
	if section, ok := config["server"].(map[string]interface{}); ok {
		if value, ok := section["writetimeout"].(int); ok {
			return value
		}
	}

	return defaultValue
}


// ===== Mock Implementation =====

type serverMockConfig struct{}


func (c *serverMockConfig) Port(defaultValue int) int {
	return defaultValue
}

func (c *serverMockConfig) Host(defaultValue string) string {
	return defaultValue
}

func (c *serverMockConfig) ReadTimeout(defaultValue int) int {
	return defaultValue
}

func (c *serverMockConfig) WriteTimeout(defaultValue int) int {
	return defaultValue
}


func NewServerConfigMock() *serverMockConfig {
	return &serverMockConfig{}
}

// ===== Composite Implementation =====

type serverAllConfig struct {
	sources []interface{
		Port(defaultValue int) int
		Host(defaultValue string) string
		ReadTimeout(defaultValue int) int
		WriteTimeout(defaultValue int) int
	}
}

func NewServerConfigAll(sources ...interface{
	Port(defaultValue int) int
	Host(defaultValue string) string
	ReadTimeout(defaultValue int) int
	WriteTimeout(defaultValue int) int
}) *serverAllConfig {
	return &serverAllConfig{sources: sources}
}


func (c *serverAllConfig) Port(defaultValue int) int {
	sentinel := -2147483648
	for _, s := range c.sources {
		v := s.Port(sentinel)
		if v != sentinel {
			return v
		}
	}
	return defaultValue
}

func (c *serverAllConfig) Host(defaultValue string) string {
	sentinel := "__GGCONFIG_SENTINEL__"
	for _, s := range c.sources {
		v := s.Host(sentinel)
		if v != sentinel {
			return v
		}
	}
	return defaultValue
}

func (c *serverAllConfig) ReadTimeout(defaultValue int) int {
	sentinel := -2147483648
	for _, s := range c.sources {
		v := s.ReadTimeout(sentinel)
		if v != sentinel {
			return v
		}
	}
	return defaultValue
}

func (c *serverAllConfig) WriteTimeout(defaultValue int) int {
	sentinel := -2147483648
	for _, s := range c.sources {
		v := s.WriteTimeout(sentinel)
		if v != sentinel {
			return v
		}
	}
	return defaultValue
}

