// Code generated by ggconfig. DO NOT EDIT.

package db

import (
	
	"os"
	
	"github.com/apopov-app/ggconfig/runtime"
	
)

// ===== ENV Implementation =====

type internal_dbEnvConfig struct{
	mapKey func(string) string
}


func (c *internal_dbEnvConfig) Host(defaultValue string) (string, bool) {
	if value := os.Getenv(c.mapKey("INTERNAL_DB_HOST")); value != "" {
		return value, true
	}
	return defaultValue, false
}

func (c *internal_dbEnvConfig) Port(defaultValue string) (string, bool) {
	if value := os.Getenv(c.mapKey("INTERNAL_DB_PORT")); value != "" {
		return value, true
	}
	return defaultValue, false
}

func (c *internal_dbEnvConfig) User(defaultValue string) (string, bool) {
	if value := os.Getenv(c.mapKey("INTERNAL_DB_USER")); value != "" {
		return value, true
	}
	return defaultValue, false
}

func (c *internal_dbEnvConfig) Password(defaultValue string) (string, bool) {
	if value := os.Getenv(c.mapKey("INTERNAL_DB_PASSWORD")); value != "" {
		return value, true
	}
	return defaultValue, false
}

func (c *internal_dbEnvConfig) Name(defaultValue string) (string, bool) {
	if value := os.Getenv(c.mapKey("INTERNAL_DB_NAME")); value != "" {
		return value, true
	}
	return defaultValue, false
}

func (c *internal_dbEnvConfig) SSLMode(defaultValue string) (string, bool) {
	if value := os.Getenv(c.mapKey("INTERNAL_DB_SSL_MODE")); value != "" {
		return value, true
	}
	return defaultValue, false
}


func NewInternalDbConfigEnvConfig() *internal_dbEnvConfig {
	return NewInternalDbConfigEnvConfigWithMap(nil)
}

func NewInternalDbConfigEnvConfigWithMap(mapKey func(string) string) *internal_dbEnvConfig {
	if mapKey == nil {
		mapKey = func(k string) string { return k }
	}
	return &internal_dbEnvConfig{mapKey: mapKey}
}

// ===== YAML Implementation =====

type internal_dbYAMLConfig struct {
	y *runtime.YAML
	err error
}

func NewInternalDbConfigYAMLConfig(path string) *internal_dbYAMLConfig {
	b, err := os.ReadFile(path)
	if err != nil {
		return &internal_dbYAMLConfig{y: &runtime.YAML{}, err: err}
	}
	y, err := runtime.ParseYAML(b)
	if err != nil {
		return &internal_dbYAMLConfig{y: &runtime.YAML{}, err: err}
	}
	return &internal_dbYAMLConfig{y: y}
}

func NewInternalDbConfigYAMLConfigParsed(y *runtime.YAML) *internal_dbYAMLConfig {
	return &internal_dbYAMLConfig{
		y: y,
	}
}

func (c *internal_dbYAMLConfig) Err() error { return c.err }


func (c *internal_dbYAMLConfig) Host(defaultValue string) (string, bool) {
	// Алиасные секции
	// Основная секция internal_db
	if v, ok := c.y.GetString("internal_db", "host"); ok {
		return v, true
		}
	return defaultValue, false
}

func (c *internal_dbYAMLConfig) Port(defaultValue string) (string, bool) {
	// Алиасные секции
	// Основная секция internal_db
	if v, ok := c.y.GetString("internal_db", "port"); ok {
		return v, true
		}
	return defaultValue, false
}

func (c *internal_dbYAMLConfig) User(defaultValue string) (string, bool) {
	// Алиасные секции
	// Основная секция internal_db
	if v, ok := c.y.GetString("internal_db", "user"); ok {
		return v, true
		}
	return defaultValue, false
}

func (c *internal_dbYAMLConfig) Password(defaultValue string) (string, bool) {
	// Алиасные секции
	// Основная секция internal_db
	if v, ok := c.y.GetString("internal_db", "password"); ok {
		return v, true
		}
	return defaultValue, false
}

func (c *internal_dbYAMLConfig) Name(defaultValue string) (string, bool) {
	// Алиасные секции
	// Основная секция internal_db
	if v, ok := c.y.GetString("internal_db", "name"); ok {
		return v, true
		}
	return defaultValue, false
}

func (c *internal_dbYAMLConfig) SSLMode(defaultValue string) (string, bool) {
	// Алиасные секции
	// Основная секция internal_db
	if v, ok := c.y.GetString("internal_db", "sslmode"); ok {
		return v, true
		}
	return defaultValue, false
}


// ===== Mock Implementation =====

type internal_dbMockConfig struct{}


func (c *internal_dbMockConfig) Host(defaultValue string) (string, bool) {
	return defaultValue, false
}

func (c *internal_dbMockConfig) Port(defaultValue string) (string, bool) {
	return defaultValue, false
}

func (c *internal_dbMockConfig) User(defaultValue string) (string, bool) {
	return defaultValue, false
}

func (c *internal_dbMockConfig) Password(defaultValue string) (string, bool) {
	return defaultValue, false
}

func (c *internal_dbMockConfig) Name(defaultValue string) (string, bool) {
	return defaultValue, false
}

func (c *internal_dbMockConfig) SSLMode(defaultValue string) (string, bool) {
	return defaultValue, false
}


func NewInternalDbConfigMock() *internal_dbMockConfig {
	return &internal_dbMockConfig{}
}

// ===== Composite Implementation =====

type internal_dbAllConfig struct {
	sources []interface{
		Host(defaultValue string) (string, bool)
		Port(defaultValue string) (string, bool)
		User(defaultValue string) (string, bool)
		Password(defaultValue string) (string, bool)
		Name(defaultValue string) (string, bool)
		SSLMode(defaultValue string) (string, bool)
	}
}

func NewInternalDbConfigAll(sources ...interface{
	Host(defaultValue string) (string, bool)
	Port(defaultValue string) (string, bool)
	User(defaultValue string) (string, bool)
	Password(defaultValue string) (string, bool)
	Name(defaultValue string) (string, bool)
	SSLMode(defaultValue string) (string, bool)
}) *internal_dbAllConfig {
	return &internal_dbAllConfig{sources: sources}
}


func (c *internal_dbAllConfig) Host(defaultValue string) (string, bool) {
	for _, s := range c.sources {
		v, ok := s.Host(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *internal_dbAllConfig) Port(defaultValue string) (string, bool) {
	for _, s := range c.sources {
		v, ok := s.Port(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *internal_dbAllConfig) User(defaultValue string) (string, bool) {
	for _, s := range c.sources {
		v, ok := s.User(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *internal_dbAllConfig) Password(defaultValue string) (string, bool) {
	for _, s := range c.sources {
		v, ok := s.Password(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *internal_dbAllConfig) Name(defaultValue string) (string, bool) {
	for _, s := range c.sources {
		v, ok := s.Name(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *internal_dbAllConfig) SSLMode(defaultValue string) (string, bool) {
	for _, s := range c.sources {
		v, ok := s.SSLMode(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}



