// Code generated by ggconfig. DO NOT EDIT.

package gconfig

import (
	
	"os"
	"strconv"
	"github.com/apopov-app/ggconfig/runtime"
	
)

// ===== ENV Implementation =====

type cmd_Abin_internal_serverEnvConfig struct{
	mapKey func(string) string
}


func (c *cmd_Abin_internal_serverEnvConfig) Port(defaultValue int) (int, bool) {
	if value := os.Getenv(c.mapKey("SERVER_PORT")); value != "" {
		if intValue, err := strconv.Atoi(value); err == nil {
			return intValue, true
		}
	}
	return defaultValue, false
}

func (c *cmd_Abin_internal_serverEnvConfig) Host(defaultValue string) (string, bool) {
	if value := os.Getenv(c.mapKey("SERVER_HOST")); value != "" {
		return value, true
	}
	return defaultValue, false
}


func NewCmdAbinInternalServerConfigEnvConfig() *cmd_Abin_internal_serverEnvConfig {
	return NewCmdAbinInternalServerConfigEnvConfigWithMap(nil)
}

func NewCmdAbinInternalServerConfigEnvConfigWithMap(mapKey func(string) string) *cmd_Abin_internal_serverEnvConfig {
	if mapKey == nil {
		mapKey = func(k string) string { return k }
	}
	return &cmd_Abin_internal_serverEnvConfig{mapKey: mapKey}
}

// ===== YAML Implementation =====

type cmd_Abin_internal_serverYAMLConfig struct {
	y *runtime.YAML
	err error
}

func NewCmdAbinInternalServerConfigYAMLConfig(path string) *cmd_Abin_internal_serverYAMLConfig {
	b, err := os.ReadFile(path)
	if err != nil {
		return &cmd_Abin_internal_serverYAMLConfig{y: &runtime.YAML{}, err: err}
	}
	y, err := runtime.ParseYAML(b)
	if err != nil {
		return &cmd_Abin_internal_serverYAMLConfig{y: &runtime.YAML{}, err: err}
	}
	return &cmd_Abin_internal_serverYAMLConfig{y: y}
}

func NewCmdAbinInternalServerConfigYAMLConfigParsed(y *runtime.YAML) *cmd_Abin_internal_serverYAMLConfig {
	return &cmd_Abin_internal_serverYAMLConfig{
		y: y,
	}
}

func (c *cmd_Abin_internal_serverYAMLConfig) Err() error { return c.err }


func (c *cmd_Abin_internal_serverYAMLConfig) Port(defaultValue int) (int, bool) {
	// Алиасные секции
	
	// Основная секция server
	if v, ok := c.y.GetInt("server", "port"); ok {
		return v, true
	}
	return defaultValue, false
}

func (c *cmd_Abin_internal_serverYAMLConfig) Host(defaultValue string) (string, bool) {
	// Алиасные секции
	
	// Основная секция server
	if v, ok := c.y.GetString("server", "host"); ok {
		return v, true
		}
	return defaultValue, false
}


// ===== Mock Implementation =====

type cmd_Abin_internal_serverMockConfig struct{}


func (c *cmd_Abin_internal_serverMockConfig) Port(defaultValue int) (int, bool) {
	return defaultValue, false
}

func (c *cmd_Abin_internal_serverMockConfig) Host(defaultValue string) (string, bool) {
	return defaultValue, false
}


func NewCmdAbinInternalServerConfigMock() *cmd_Abin_internal_serverMockConfig {
	return &cmd_Abin_internal_serverMockConfig{}
}

// ===== Composite Implementation =====

type cmd_Abin_internal_serverAllConfig struct {
	sources []interface{
		Port(defaultValue int) (int, bool)
		Host(defaultValue string) (string, bool)
	}
}

func NewCmdAbinInternalServerConfigAll(sources ...interface{
	Port(defaultValue int) (int, bool)
	Host(defaultValue string) (string, bool)
}) *cmd_Abin_internal_serverAllConfig {
	return &cmd_Abin_internal_serverAllConfig{sources: sources}
}


func (c *cmd_Abin_internal_serverAllConfig) Port(defaultValue int) (int, bool) {
	for _, s := range c.sources {
		v, ok := s.Port(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}

func (c *cmd_Abin_internal_serverAllConfig) Host(defaultValue string) (string, bool) {
	for _, s := range c.sources {
		v, ok := s.Host(defaultValue)
		if ok {
			return v, true
		}
	}
	return defaultValue, false
}



func init() {
	Register("cmd_Abin_internal_server", Provider{
		Package: "cmd_Abin_internal_server",
		NewAllFromParsed: func(y *runtime.YAML, mapKey func(string) string) any {
			envCfg := NewCmdAbinInternalServerConfigEnvConfigWithMap(mapKey)
			yamlCfg := NewCmdAbinInternalServerConfigYAMLConfigParsed(y)
			return NewCmdAbinInternalServerConfigAll(envCfg, yamlCfg)
		},
	})
}

// GetCmdAbinInternalServer returns the concrete AllConfig type for this package.
// It can be passed anywhere the original interface is expected (structural typing).
func (g *GlobalConfig) GetCmdAbinInternalServer() (*cmd_Abin_internal_serverAllConfig, bool) {
	registryMu.RLock()
	p, ok := registry["cmd_Abin_internal_server"]
	registryMu.RUnlock()
	if !ok || p.NewAllFromParsed == nil {
		return nil, false
	}
	v := p.NewAllFromParsed(g.y, g.mapKey)
	cfg, ok := v.(*cmd_Abin_internal_serverAllConfig)
	return cfg, ok
}

